#!/usr/bin/env python

import rospy
import actionlib_msgs.msg

rospy.init_node("move_base_cancel")

cancel_publisher = rospy.Publisher("/move_base/cancel", actionlib_msgs.msg.GoalID, queue_size=32, latch=True)

rospy.sleep(1.0)

finished = False

def callback(msg):
    global finished, cancel_publisher
    if not finished:
        for goal in msg.status_list:
            print "canceling", goal.goal_id.id
            cancel_publisher.publish(goal.goal_id)
        finished = True

status_subscriber = rospy.Subscriber("/move_base/status", actionlib_msgs.msg.GoalStatusArray, callback, queue_size=1)

while not rospy.is_shutdown() and not finished:
    rospy.sleep(0.1)

rospy.sleep(3)
