# type of the target in the planning scene
string target_type
# the pose relative to which the closest target is searched
geometry_msgs/PoseStamped target_pose
# should the robot look in the direction of the target pose while driving?
bool look_at_target
---
# the pose the robot moved to
geometry_msgs/PoseStamped pose_result
# the pose of the target in the planning scene
geometry_msgs/PoseStamped target_pose_result
string target_id
---
