#goal definition
duration timeout
---
#result definition
string selection
string status
---
#feedback
string current_selection
float32 selection_counter
uint32 feature_matches
uint32 detection_failures
