recipes:
  tequila_sunrise:
    - tequila: 1.0
    - orange: 1.0
    - cherry: 1.0
  cuba_libre:
    - rum: 1.0
    - coke: 1.0
  sunrise:
    - orange: 1.0
    - cherry: 1.0
  driver:
    - orange: 1.0
    - cherry: 1.0
    - lime: 1.0
  water:
    - water: 1.0
  sulfuric_acid:
    - acid: 1.0

idle_zone:
  center_x: 0.0
  center_y: 0.0
  radius_x: 0.2
  radius_y: 0.5
  euler_z: 0.0
  frame: 'map'

home_pose:
  pos_x: 0.0
  pos_y: 0.0
  ori_x: 0.0
  ori_y: 0.0
  ori_z: 0.0
  ori_w: 1.0
  frame: 'map'

take_order_pose:
  pos_x: 0.4
  pos_y: 0.0
  ori_x: 0.0
  ori_y: 0.0
  ori_z: 0.0
  ori_w: 1.0
  frame: 'map'

place_bottle_offset:
  x: 0.15
  y: 0.0
  frame: 'table1'

customer_zone:
  frame: 'map'
  center_x: 2.65
  center_y: 0.0
  center_z: 1.5
  euler_z: 0.0
  size_x: 3.0
  size_y: 2.20
  size_z: 1.2

scene_objects:
  ids:
    - 'table1'
    - 'table2'
    - 'rum'
    - 'water'
    - 'coke'
    - 'tequila'
    - 'orange'
    - 'glass'
  types:
    - 'small_table'
    - 'large_table'
    - 'bottle'
    - 'bottle'
    - 'bottle'
    - 'bottle'
    - 'bottle'
    - 'glass'
  pos_x:
    - -1.25
    - 1.25
    - -1.20
    - -1.20
    - -1.20
    - -1.20
    - -1.20
    - 1.25
  pos_y:
    - -0.1
    - 0.0
    - -0.7
    - -0.4
    - -0.1
    - 0.2
    - 0.5
    - -0.3
  pos_z:
    - 0.0
    - 0.0
    - 0.875
    - 0.875
    - 0.875
    - 0.875
    - 0.875
    - 0.8
  frame:
    - 'map'
    - 'map'
    - 'map'
    - 'map'
    - 'map'
    - 'map'
    - 'map'
    - 'map'
