recipes:
  tequila_sunrise:
    - tequila: 1.0
    - orange: 5.0
    - cherry: 1.0
  cuba_libre:
    - rum: 1.0
    - coke: 5.0
  sunrise:
    - orange: 5.0
    - cherry: 1.0
  driver:
    - orange: 5.0
    - cherry: 1.0
    - lime: 1.0
  water:
    - water: 5.0
  sulfuric_acid:
    - acid: 30.0

idle_zone:
  center_x: 0.0
  center_y: 0.0
  radius_x: 0.2
  radius_y: 0.5
  euler_z: 0.0
  frame: 'map'

home_pose:
  pos_x: 0.0
  pos_y: 0.0
  ori_x: 0.0
  ori_y: 0.0
  ori_z: 0.0
  ori_w: 1.0
  frame: 'map'

take_order_pose:
  pos_x: 0.4
  pos_y: 0.0
  ori_x: 0.0
  ori_y: 0.0
  ori_z: 0.0
  ori_w: 1.0
  frame: 'map'

place_bottle_offset:
  x: 0.15
  y: 0.0
  frame: 'table1'

customer_zone:
  frame: 'map'
  center_x: 1.65
  center_y: 0.0
  center_z: 1.5
  euler_z: 0.0
  size_x: 1.0
  size_y: 2.20
  size_z: 1.2

look_at:
  update_person_pose: false
  max_head_velocity: 3.0

scene_objects:
  table1:
      frame: 'map'
      type: small_table
      pos_x: -1.25
      pos_y: -0.1
      pos_z: 0.0
  table2:
      frame: 'map'
      type: large_table
      pos_x: 1.25
      pos_y: 0.0
      pos_z: 0.0
  rum:
      frame: 'map'
      type: bottle
      pos_x: -1.20
      pos_y: -0.7
      pos_z: 0.875
  water:
      frame: 'map'
      type: bottle
      pos_x: -1.20
      pos_y: -0.4
      pos_z: 0.875
  coke:
      frame: 'map'
      type: bottle
      pos_x: -1.20
      pos_y: -0.1
      pos_z: 0.875
  tequila:
      frame: 'map'
      type: bottle
      pos_x: -1.20
      pos_y: 0.2
      pos_z: 0.875
  orange:
      frame: 'map'
      type: bottle
      pos_x: -1.20
      pos_y: 0.5
      pos_z: 0.875
  glass:
      frame: 'map'
      type: glass
      pos_x: 1.1
      pos_y: -0.3
      pos_z: 0.8

move_to_target_lines:
  in_front_of_bottles:
    start_point_x: -0.55
    start_point_y: 1.0
    end_point_x: -0.55
    end_point_y: -1.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 1.0
    orientation_w: 0.0
  in_front_of_glass:
    start_point_x: 0.4
    start_point_y: 1.0
    end_point_x: 0.4
    end_point_y: -1.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
